# Generated by Django 3.0.4 on 2020-04-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Miejscowość')),
            ],
            options={
                'verbose_name': 'Miejscowość',
                'verbose_name_plural': 'Miejscowości',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ulica',
                'verbose_name_plural': 'Ulice',
                'ordering': ('name',),
            },
        ),
    ]
