# Generated by Django 3.0.7 on 2020-06-21 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 10, 0, 0), verbose_name='Data utworzenia'),
            preserve_default=False,
        ),
    ]
