# Generated by Django 3.0.4 on 2020-04-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_detail', '0002_auto_20200402_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='city_detail.City', verbose_name='Miasto')),
                ('street', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='city_detail.Street', verbose_name='Ulica')),
            ],
            options={
                'verbose_name': 'Adres odbioru odpadów',
                'verbose_name_plural': 'Adresy odbioru odpadów',
                'unique_together': {('city', 'street')},
            },
        ),
    ]
