# Generated by Django 3.0.4 on 2020-04-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_detail', '0005_address_city_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city_type',
        ),
        migrations.AddField(
            model_name='city',
            name='city_type',
            field=models.CharField(choices=[('gmina', 'Gmina'), ('miasto', 'Miasto')], default='gmina', max_length=10, verbose_name='Typ miejscowości'),
        ),
    ]
