version: '3'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python rubbish_collection_day_2_root/manage.py makemigrations && python rubbish_collection_day_2_root/manage.py migrate && python rubbish_collection_day_2_root/manage.py runserver 0.0.0.0:8000
    container_name: rubbish_collection_day_2
    volumes:
      - ./rubbish_collection_day_2_root:/rubbish_collection_day_2
    ports:
      - "8000:8000" 
    depends_on:
        - db