version: '3'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.pl
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    links:
      - "db:pgsql-server"
  web:
    build: .
    container_name: rubbish_collection_day_2
    volumes:
      - ./rubbish_collection_day_2_root:/code
    ports:
      - "8000:8000" 
    depends_on:
      - db