# Generated by Django 3.0.4 on 2020-04-04 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city_detail', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Daty',
            },
        ),
        migrations.CreateModel(
            name='RubbishType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa frakcji')),
                ('mark_color', models.CharField(max_length=7, verbose_name='Kolor zaznaczenia w kalendarzu')),
            ],
        ),
        migrations.CreateModel(
            name='RubbishDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Rejon')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts', to='city_detail.Address')),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts', to='schedule.Date')),
                ('rubbish_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts', to='schedule.RubbishType')),
            ],
        ),
    ]
