# Generated by Django 3.0.4 on 2020-04-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubbishdistrict',
            name='city_type',
            field=models.CharField(choices=[('gmina', 'Gmina'), ('miasto', 'Miasto')], default='gmina', max_length=10, verbose_name='Typ miejscowości'),
        ),
    ]
