# Generated by Django 3.1 on 2020-08-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfiguration',
            name='last_update',
            field=models.CharField(default='marzec 2020', max_length=100, verbose_name='Nazwa strony'),
        ),
    ]
