# Generated by Django 3.0.4 on 2020-04-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rubbishdistrict_city_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubbishtype',
            options={'verbose_name': 'Frakcja', 'verbose_name_plural': 'Frakcje śmieci'},
        ),
        migrations.AlterField(
            model_name='rubbishtype',
            name='mark_color',
            field=models.CharField(max_length=7, unique=True, verbose_name='Kolor zaznaczenia w kalendarzu'),
        ),
    ]
