# Generated by Django 3.0.4 on 2020-04-04 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20200404_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubbishdistrict',
            options={'verbose_name': 'Rejon', 'verbose_name_plural': 'Rejony odbioru odpadów'},
        ),
    ]
