# Generated by Django 3.1 on 2020-08-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_scheduleconfiguration_gtm_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleconfiguration',
            name='add_gtm',
            field=models.BooleanField(default=False, verbose_name='Google Tag Manager (GTM)'),
        ),
    ]
