# Generated by Django 3.0.4 on 2020-04-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20200404_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubbishdistrict',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='rubbishdistrict',
            name='rubbish_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts', to='schedule.RubbishType', verbose_name='Frakcja'),
        ),
        migrations.AlterField(
            model_name='rubbishtype',
            name='mark_color',
            field=models.CharField(help_text='Podaj HEX zaczynająć od #. ', max_length=7, unique=True, verbose_name='Kolor zaznaczenia w kalendarzu'),
        ),
        migrations.AlterUniqueTogether(
            name='rubbishdistrict',
            unique_together={('name', 'city_type', 'rubbish_type')},
        ),
        migrations.RemoveField(
            model_name='rubbishdistrict',
            name='address',
        ),
    ]
