# Generated by Django 3.0.4 on 2020-04-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20200404_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255, verbose_name='Nazwa strony')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Przerwa techniczna')),
                ('year', models.CharField(max_length=4, unique=True, verbose_name='Rok')),
                ('original_schedule', models.CharField(help_text='Link do harmonogramu opublikowanego na stronie Urzędu Miasta', max_length=255, verbose_name='Link do harmonogramu')),
            ],
            options={
                'verbose_name': 'Konfiguracja',
            },
        ),
        migrations.RemoveField(
            model_name='rubbishdistrict',
            name='date',
        ),
        migrations.AddField(
            model_name='rubbishdistrict',
            name='date',
            field=models.ManyToManyField(blank=True, related_name='districts', to='schedule.Date', verbose_name='Daty'),
        ),
    ]
