# Generated by Django 3.0.4 on 2020-04-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20200404_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubbishdistrict',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa rejonu'),
        ),
    ]
