# Generated by Django 3.0.4 on 2020-04-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20200404_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleconfiguration',
            options={'verbose_name': 'Konfiguracja harmonogramu'},
        ),
    ]
