# Generated by Django 3.0.4 on 2020-04-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20200413_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubbishtype',
            name='css_name',
            field=models.CharField(blank=True, help_text='Trzy litery związane z nazwą frakcji.', max_length=3, verbose_name='Skrótowa nazwa frakcji'),
        ),
    ]
