# Generated by Django 3.0.4 on 2020-05-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20200425_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconfiguration',
            name='original_schedule',
            field=models.CharField(help_text='Link do harmonogramu opublikowanego na stronie UM', max_length=255, verbose_name='Link do harmonogramu'),
        ),
        migrations.AlterField(
            model_name='scheduleconfiguration',
            name='year',
            field=models.IntegerField(max_length=4, unique=True, verbose_name='Rok'),
        ),
    ]
