# Generated by Django 3.0.4 on 2020-05-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20200504_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconfiguration',
            name='year',
            field=models.IntegerField(unique=True, verbose_name='Rok'),
        ),
    ]
