# Generated by Django 3.0.4 on 2020-05-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20200504_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleconfiguration',
            name='original_schedule',
            field=models.CharField(default='localhost', help_text='Link do harmonogramu opublikowanego na stronie UM', max_length=255, verbose_name='Link do harmonogramu'),
        ),
        migrations.AlterField(
            model_name='scheduleconfiguration',
            name='site_name',
            field=models.CharField(default='Calendar', max_length=255, verbose_name='Nazwa strony'),
        ),
        migrations.AlterField(
            model_name='scheduleconfiguration',
            name='year',
            field=models.IntegerField(default=2020, unique=True, verbose_name='Rok'),
        ),
    ]
