# Generated by Django 2.1 on 2018-12-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webpage',
            options={'verbose_name': 'Strona', 'verbose_name_plural': 'Strony'},
        ),
        migrations.AddField(
            model_name='webpage',
            name='meta_description',
            field=models.CharField(default='Meta', max_length=250),
            preserve_default=False,
        ),
    ]
