# Generated by Django 2.1 on 2018-12-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_pages', '0002_auto_20181207_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='meta_description',
            field=models.TextField(max_length=250),
        ),
    ]
